/* SimMechanics target specific file
 *      This file generated a part of SimMechanics code generation.
 */
#include "tmwtypes.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "mtypes.h"
#include "simulation_data.h"
#include "sim_mechanics_imports.h"
/* rt_mechanism.c - body for module rt_mechanism */
#include "rt_mechanism.h"
#include "rt_mechanism_map.h"
int32_T rt_mech_visited_vmrl_test_fourbar_1d6fdf5b = 0;
int32_T rt_mech_visited_loc_vmrl_test_fourbar_1d6fdf5b = 0;
Mechanism *rt_get_mechanism_vmrl_test_fourbar_1d6fdf5b(void)
{
    static Mechanism *_mechanism = 0;
    static pmArrayRead pmArrayRead_table[74];
    static real_T real_T_table[649];
    static AxisRead AxisRead_table[4];
    static pmArrayRead *pmArrayRead_ptr_table[24];
    static NameArrayRead NameArrayRead_table[7];
    static int32_T int32_T_table[38];
    static IndexArrayRead IndexArrayRead_table[21];
    static Sensor Sensor_table[6];
    static BodySensor BodySensor_table[6];
    static BodyActuator BodyActuator_table[12];
    static GeneralJointEngine GeneralJointEngine_table[7];
    static Joint Joint_table[6];
    static BodyEngine BodyEngine_table[6];
    static Body Body_table[6];
    static Joint *Joint_ptr_table[6];
    static Constraint Constraint_table[1];
    static Branch Branch_table[3];
    static Body *Body_ptr_table[6];
    static Connect Connect_table[1];
    static Branch *Branch_ptr_table[8];
    static Recursion Recursion_table[1];
    static Connect *Connect_ptr_table[1];
    static MachineData MachineData_table[1];
    static WarningFlags WarningFlags_table[1];
    static Mechanism Mechanism_table[1];
    static Constraint *Constraint_ptr_table[1];
    if(_mechanism == 0) {
        /* starting table: pmArrayRead_table */
        memset(pmArrayRead_table, 0, sizeof(pmArrayRead_table));
        pmArrayRead_table[0].iszero = 1;
        pmArrayRead_table[0].type = 1;
        pmArrayRead_table[1].iszero = 1;
        pmArrayRead_table[1].type = 1;
        pmArrayRead_table[1].n = 3U;
        pmArrayRead_table[1].real = real_T_table + 10U;
        pmArrayRead_table[2].type = 1;
        pmArrayRead_table[2].n = 3U;
        pmArrayRead_table[2].real = real_T_table + 13U;
        pmArrayRead_table[3].type = 1;
        pmArrayRead_table[3].n = 3U;
        pmArrayRead_table[3].real = real_T_table + 388U;
        pmArrayRead_table[4].type = 1;
        pmArrayRead_table[4].n = 1U;
        pmArrayRead_table[4].real = real_T_table + 391U;
        pmArrayRead_table[5].type = 1;
        pmArrayRead_table[5].n = 9U;
        pmArrayRead_table[5].real = real_T_table + 392U;
        pmArrayRead_table[6].type = 1;
        pmArrayRead_table[6].n = 3U;
        pmArrayRead_table[6].real = real_T_table + 401U;
        pmArrayRead_table[7].type = 1;
        pmArrayRead_table[7].n = 9U;
        pmArrayRead_table[7].real = real_T_table + 404U;
        pmArrayRead_table[8].type = 1;
        pmArrayRead_table[8].n = 1U;
        pmArrayRead_table[8].real = real_T_table + 413U;
        pmArrayRead_table[9].type = 1;
        pmArrayRead_table[9].n = 9U;
        pmArrayRead_table[9].real = real_T_table + 414U;
        pmArrayRead_table[10].type = 1;
        pmArrayRead_table[10].n = 3U;
        pmArrayRead_table[10].real = real_T_table + 423U;
        pmArrayRead_table[11].type = 1;
        pmArrayRead_table[11].n = 9U;
        pmArrayRead_table[11].real = real_T_table + 426U;
        pmArrayRead_table[12].type = 1;
        pmArrayRead_table[12].n = 3U;
        pmArrayRead_table[12].real = real_T_table + 435U;
        pmArrayRead_table[13].type = 1;
        pmArrayRead_table[13].n = 9U;
        pmArrayRead_table[13].real = real_T_table + 438U;
        pmArrayRead_table[14].type = 1;
        pmArrayRead_table[14].n = 1U;
        pmArrayRead_table[14].real = real_T_table + 447U;
        pmArrayRead_table[15].type = 1;
        pmArrayRead_table[15].n = 9U;
        pmArrayRead_table[15].real = real_T_table + 448U;
        pmArrayRead_table[16].type = 1;
        pmArrayRead_table[16].n = 3U;
        pmArrayRead_table[16].real = real_T_table + 457U;
        pmArrayRead_table[17].type = 1;
        pmArrayRead_table[17].n = 9U;
        pmArrayRead_table[17].real = real_T_table + 460U;
        pmArrayRead_table[18].type = 1;
        pmArrayRead_table[18].n = 3U;
        pmArrayRead_table[18].real = real_T_table + 469U;
        pmArrayRead_table[19].type = 1;
        pmArrayRead_table[19].n = 9U;
        pmArrayRead_table[19].real = real_T_table + 472U;
        pmArrayRead_table[20].type = 1;
        pmArrayRead_table[20].n = 1U;
        pmArrayRead_table[20].real = real_T_table + 481U;
        pmArrayRead_table[21].type = 1;
        pmArrayRead_table[21].n = 9U;
        pmArrayRead_table[21].real = real_T_table + 482U;
        pmArrayRead_table[22].type = 1;
        pmArrayRead_table[22].n = 3U;
        pmArrayRead_table[22].real = real_T_table + 491U;
        pmArrayRead_table[23].type = 1;
        pmArrayRead_table[23].n = 9U;
        pmArrayRead_table[23].real = real_T_table + 494U;
        pmArrayRead_table[24].type = 1;
        pmArrayRead_table[24].n = 3U;
        pmArrayRead_table[24].real = real_T_table + 503U;
        pmArrayRead_table[25].type = 1;
        pmArrayRead_table[25].n = 9U;
        pmArrayRead_table[25].real = real_T_table + 506U;
        pmArrayRead_table[26].type = 1;
        pmArrayRead_table[26].n = 1U;
        pmArrayRead_table[26].real = real_T_table + 515U;
        pmArrayRead_table[27].type = 1;
        pmArrayRead_table[27].n = 9U;
        pmArrayRead_table[27].real = real_T_table + 516U;
        pmArrayRead_table[28].type = 1;
        pmArrayRead_table[28].n = 3U;
        pmArrayRead_table[28].real = real_T_table + 525U;
        pmArrayRead_table[29].type = 1;
        pmArrayRead_table[29].n = 9U;
        pmArrayRead_table[29].real = real_T_table + 528U;
        pmArrayRead_table[30].type = 1;
        pmArrayRead_table[30].n = 3U;
        pmArrayRead_table[30].real = real_T_table + 537U;
        pmArrayRead_table[31].type = 1;
        pmArrayRead_table[31].n = 9U;
        pmArrayRead_table[31].real = real_T_table + 540U;
        pmArrayRead_table[32].type = 1;
        pmArrayRead_table[32].n = 1U;
        pmArrayRead_table[32].real = real_T_table + 549U;
        pmArrayRead_table[33].type = 1;
        pmArrayRead_table[33].n = 9U;
        pmArrayRead_table[33].real = real_T_table + 550U;
        pmArrayRead_table[34].type = 1;
        pmArrayRead_table[34].n = 3U;
        pmArrayRead_table[34].real = real_T_table + 559U;
        pmArrayRead_table[35].type = 1;
        pmArrayRead_table[35].n = 9U;
        pmArrayRead_table[35].real = real_T_table + 562U;
        pmArrayRead_table[36].type = 1;
        pmArrayRead_table[36].n = 1U;
        pmArrayRead_table[36].real = real_T_table + 571U;
        pmArrayRead_table[37].type = 1;
        pmArrayRead_table[37].n = 1U;
        pmArrayRead_table[37].real = real_T_table + 572U;
        pmArrayRead_table[38].type = 1;
        pmArrayRead_table[38].n = 1U;
        pmArrayRead_table[38].real = real_T_table + 573U;
        pmArrayRead_table[39].type = 1;
        pmArrayRead_table[39].n = 3U;
        pmArrayRead_table[39].real = real_T_table + 574U;
        pmArrayRead_table[40].type = 1;
        pmArrayRead_table[40].n = 3U;
        pmArrayRead_table[40].real = real_T_table + 577U;
        pmArrayRead_table[41].type = 1;
        pmArrayRead_table[41].n = 1U;
        pmArrayRead_table[41].real = real_T_table + 580U;
        pmArrayRead_table[42].type = 1;
        pmArrayRead_table[42].n = 1U;
        pmArrayRead_table[42].real = real_T_table + 581U;
        pmArrayRead_table[43].type = 1;
        pmArrayRead_table[43].n = 1U;
        pmArrayRead_table[43].real = real_T_table + 582U;
        pmArrayRead_table[44].type = 1;
        pmArrayRead_table[44].n = 3U;
        pmArrayRead_table[44].real = real_T_table + 583U;
        pmArrayRead_table[45].type = 1;
        pmArrayRead_table[45].n = 3U;
        pmArrayRead_table[45].real = real_T_table + 586U;
        pmArrayRead_table[46].type = 1;
        pmArrayRead_table[46].n = 3U;
        pmArrayRead_table[46].real = real_T_table + 589U;
        pmArrayRead_table[47].type = 1;
        pmArrayRead_table[47].n = 1U;
        pmArrayRead_table[47].real = real_T_table + 592U;
        pmArrayRead_table[48].type = 1;
        pmArrayRead_table[48].n = 1U;
        pmArrayRead_table[48].real = real_T_table + 593U;
        pmArrayRead_table[49].type = 1;
        pmArrayRead_table[49].n = 1U;
        pmArrayRead_table[49].real = real_T_table + 594U;
        pmArrayRead_table[50].type = 1;
        pmArrayRead_table[50].n = 3U;
        pmArrayRead_table[50].real = real_T_table + 595U;
        pmArrayRead_table[51].type = 1;
        pmArrayRead_table[51].n = 3U;
        pmArrayRead_table[51].real = real_T_table + 598U;
        pmArrayRead_table[52].type = 1;
        pmArrayRead_table[52].n = 3U;
        pmArrayRead_table[52].real = real_T_table + 601U;
        pmArrayRead_table[53].type = 1;
        pmArrayRead_table[53].n = 1U;
        pmArrayRead_table[53].real = real_T_table + 604U;
        pmArrayRead_table[54].type = 1;
        pmArrayRead_table[54].n = 1U;
        pmArrayRead_table[54].real = real_T_table + 605U;
        pmArrayRead_table[55].type = 1;
        pmArrayRead_table[55].n = 1U;
        pmArrayRead_table[55].real = real_T_table + 606U;
        pmArrayRead_table[56].type = 1;
        pmArrayRead_table[56].n = 3U;
        pmArrayRead_table[56].real = real_T_table + 607U;
        pmArrayRead_table[57].type = 1;
        pmArrayRead_table[57].n = 3U;
        pmArrayRead_table[57].real = real_T_table + 610U;
        pmArrayRead_table[58].type = 1;
        pmArrayRead_table[58].n = 3U;
        pmArrayRead_table[58].real = real_T_table + 613U;
        pmArrayRead_table[59].type = 1;
        pmArrayRead_table[59].n = 1U;
        pmArrayRead_table[59].real = real_T_table + 616U;
        pmArrayRead_table[60].type = 1;
        pmArrayRead_table[60].n = 1U;
        pmArrayRead_table[60].real = real_T_table + 617U;
        pmArrayRead_table[61].type = 1;
        pmArrayRead_table[61].n = 1U;
        pmArrayRead_table[61].real = real_T_table + 618U;
        pmArrayRead_table[62].type = 1;
        pmArrayRead_table[62].n = 3U;
        pmArrayRead_table[62].real = real_T_table + 619U;
        pmArrayRead_table[63].type = 1;
        pmArrayRead_table[63].n = 3U;
        pmArrayRead_table[63].real = real_T_table + 622U;
        pmArrayRead_table[64].type = 1;
        pmArrayRead_table[64].n = 1U;
        pmArrayRead_table[64].real = real_T_table + 625U;
        pmArrayRead_table[65].type = 1;
        pmArrayRead_table[65].n = 1U;
        pmArrayRead_table[65].real = real_T_table + 626U;
        pmArrayRead_table[66].type = 1;
        pmArrayRead_table[66].n = 1U;
        pmArrayRead_table[66].real = real_T_table + 627U;
        pmArrayRead_table[67].type = 1;
        pmArrayRead_table[67].n = 3U;
        pmArrayRead_table[67].real = real_T_table + 628U;
        pmArrayRead_table[68].type = 1;
        pmArrayRead_table[68].n = 3U;
        pmArrayRead_table[68].real = real_T_table + 631U;
        pmArrayRead_table[69].type = 1;
        pmArrayRead_table[69].n = 3U;
        pmArrayRead_table[69].real = real_T_table + 634U;
        pmArrayRead_table[70].type = 1;
        pmArrayRead_table[70].n = 1U;
        pmArrayRead_table[70].real = real_T_table + 637U;
        pmArrayRead_table[71].type = 1;
        pmArrayRead_table[71].n = 1U;
        pmArrayRead_table[71].real = real_T_table + 638U;
        pmArrayRead_table[72].type = 1;
        pmArrayRead_table[72].n = 1U;
        pmArrayRead_table[72].real = real_T_table + 639U;
        pmArrayRead_table[73].type = 1;
        pmArrayRead_table[73].n = 9U;
        pmArrayRead_table[73].real = real_T_table + 640U;
        /* starting table: real_T_table */
        memset(real_T_table, 0, sizeof(real_T_table));
        real_T_table[0] = 1.0;
        real_T_table[1] = 1.0;
        real_T_table[2] = 1.0;
        real_T_table[3] = 1.0;
        real_T_table[4] = 1.0;
        real_T_table[5] = 1.0;
        real_T_table[6] = 1.0;
        real_T_table[7] = 1.0;
        real_T_table[8] = 1.0;
        real_T_table[9] = 1.0;
        /* starting table: AxisRead_table */
        memset(AxisRead_table, 0, sizeof(AxisRead_table));
        AxisRead_table[0].n = 1;
        AxisRead_table[0].subaxis = pmArrayRead_ptr_table + 20U;
        AxisRead_table[1].n = 1;
        AxisRead_table[1].subaxis = pmArrayRead_ptr_table + 21U;
        AxisRead_table[2].n = 1;
        AxisRead_table[2].subaxis = pmArrayRead_ptr_table + 22U;
        AxisRead_table[3].n = 1;
        AxisRead_table[3].subaxis = pmArrayRead_ptr_table + 23U;
        /* starting table: pmArrayRead_ptr_table */
        memset(pmArrayRead_ptr_table, 0, sizeof(pmArrayRead_ptr_table));
        pmArrayRead_ptr_table[0] = pmArrayRead_table;
        pmArrayRead_ptr_table[1] = pmArrayRead_table + 19U;
        pmArrayRead_ptr_table[2] = pmArrayRead_table;
        pmArrayRead_ptr_table[3] = pmArrayRead_table + 13U;
        pmArrayRead_ptr_table[4] = pmArrayRead_table + 30U;
        pmArrayRead_ptr_table[5] = pmArrayRead_table + 30U;
        pmArrayRead_ptr_table[6] = pmArrayRead_table;
        pmArrayRead_ptr_table[7] = pmArrayRead_table + 31U;
        pmArrayRead_ptr_table[8] = pmArrayRead_table + 24U;
        pmArrayRead_ptr_table[9] = pmArrayRead_table + 24U;
        pmArrayRead_ptr_table[10] = pmArrayRead_table + 18U;
        pmArrayRead_ptr_table[11] = pmArrayRead_table + 18U;
        pmArrayRead_ptr_table[12] = pmArrayRead_table + 6U;
        pmArrayRead_ptr_table[13] = pmArrayRead_table + 6U;
        pmArrayRead_ptr_table[14] = pmArrayRead_table;
        pmArrayRead_ptr_table[15] = pmArrayRead_table + 7U;
        pmArrayRead_ptr_table[16] = pmArrayRead_table + 12U;
        pmArrayRead_ptr_table[17] = pmArrayRead_table + 12U;
        pmArrayRead_ptr_table[18] = pmArrayRead_table;
        pmArrayRead_ptr_table[19] = pmArrayRead_table + 25U;
        pmArrayRead_ptr_table[20] = pmArrayRead_table + 46U;
        pmArrayRead_ptr_table[21] = pmArrayRead_table + 52U;
        pmArrayRead_ptr_table[22] = pmArrayRead_table + 58U;
        pmArrayRead_ptr_table[23] = pmArrayRead_table + 69U;
        /* starting table: NameArrayRead_table */
        memset(NameArrayRead_table, 0, sizeof(NameArrayRead_table));
        NameArrayRead_table[0].n = 1;
        NameArrayRead_table[0].type = int32_T_table + 30U;
        NameArrayRead_table[1].n = 1;
        NameArrayRead_table[1].type = int32_T_table + 25U;
        NameArrayRead_table[2].n = 1;
        NameArrayRead_table[2].type = int32_T_table + 18U;
        NameArrayRead_table[3].n = 1;
        NameArrayRead_table[3].type = int32_T_table + 24U;
        NameArrayRead_table[4].n = 1;
        NameArrayRead_table[4].type = int32_T_table + 14U;
        NameArrayRead_table[5].n = 1;
        NameArrayRead_table[5].type = int32_T_table + 13U;
        NameArrayRead_table[6].n = 1;
        NameArrayRead_table[6].type = int32_T_table + 34U;
        /* starting table: int32_T_table */
        memset(int32_T_table, 0, sizeof(int32_T_table));
        int32_T_table[0] = 8;
        int32_T_table[1] = 1;
        int32_T_table[2] = 8;
        int32_T_table[3] = 1;
        int32_T_table[4] = 8;
        int32_T_table[5] = 1;
        int32_T_table[6] = 8;
        int32_T_table[7] = 1;
        int32_T_table[8] = 8;
        int32_T_table[9] = 1;
        int32_T_table[10] = 5;
        int32_T_table[11] = 6;
        int32_T_table[12] = 6;
        int32_T_table[13] = 2;
        int32_T_table[14] = 1;
        int32_T_table[15] = 6;
        int32_T_table[16] = 5;
        int32_T_table[17] = 3;
        int32_T_table[18] = 1;
        int32_T_table[19] = 6;
        int32_T_table[20] = 5;
        int32_T_table[21] = 3;
        int32_T_table[22] = 6;
        int32_T_table[23] = 5;
        int32_T_table[24] = 2;
        int32_T_table[25] = 2;
        int32_T_table[26] = 6;
        int32_T_table[27] = 5;
        int32_T_table[28] = 6;
        int32_T_table[29] = 6;
        int32_T_table[30] = 1;
        int32_T_table[31] = 5;
        int32_T_table[32] = 3;
        int32_T_table[33] = 6;
        int32_T_table[34] = 2;
        int32_T_table[35] = 5;
        int32_T_table[36] = 6;
        int32_T_table[37] = 6;
        /* starting table: IndexArrayRead_table */
        memset(IndexArrayRead_table, 0, sizeof(IndexArrayRead_table));
        IndexArrayRead_table[0].n = 1;
        IndexArrayRead_table[0].index = int32_T_table + 28U;
        IndexArrayRead_table[1].n = 1;
        IndexArrayRead_table[1].index = int32_T_table + 33U;
        IndexArrayRead_table[2].n = 1;
        IndexArrayRead_table[2].index = int32_T_table + 36U;
        IndexArrayRead_table[3].n = 1;
        IndexArrayRead_table[3].index = int32_T_table + 35U;
        IndexArrayRead_table[4].n = 1;
        IndexArrayRead_table[4].index = int32_T_table + 29U;
        IndexArrayRead_table[5].n = 1;
        IndexArrayRead_table[5].index = int32_T_table + 31U;
        IndexArrayRead_table[6].n = 1;
        IndexArrayRead_table[6].index = int32_T_table + 20U;
        IndexArrayRead_table[7].n = 1;
        IndexArrayRead_table[7].index = int32_T_table + 12U;
        IndexArrayRead_table[8].n = 1;
        IndexArrayRead_table[8].index = int32_T_table + 17U;
        IndexArrayRead_table[9].n = 1;
        IndexArrayRead_table[9].index = int32_T_table + 16U;
        IndexArrayRead_table[10].n = 1;
        IndexArrayRead_table[10].index = int32_T_table + 21U;
        IndexArrayRead_table[11].n = 1;
        IndexArrayRead_table[11].index = int32_T_table + 19U;
        IndexArrayRead_table[12].n = 1;
        IndexArrayRead_table[12].index = int32_T_table + 26U;
        IndexArrayRead_table[13].n = 1;
        IndexArrayRead_table[13].index = int32_T_table + 10U;
        IndexArrayRead_table[14].n = 1;
        IndexArrayRead_table[14].index = int32_T_table + 37U;
        IndexArrayRead_table[15].n = 1;
        IndexArrayRead_table[15].index = int32_T_table + 32U;
        IndexArrayRead_table[16].n = 1;
        IndexArrayRead_table[16].index = int32_T_table + 27U;
        IndexArrayRead_table[17].n = 1;
        IndexArrayRead_table[17].index = int32_T_table + 15U;
        IndexArrayRead_table[18].n = 1;
        IndexArrayRead_table[18].index = int32_T_table + 11U;
        IndexArrayRead_table[19].n = 1;
        IndexArrayRead_table[19].index = int32_T_table + 23U;
        IndexArrayRead_table[20].n = 1;
        IndexArrayRead_table[20].index = int32_T_table + 22U;
        /* starting table: Sensor_table */
        memset(Sensor_table, 0, sizeof(Sensor_table));
        /* starting table: BodySensor_table */
        memset(BodySensor_table, 0, sizeof(BodySensor_table));
        BodySensor_table[0].n = 2U;
        BodySensor_table[0].sensorType = int32_T_table + 2U;
        BodySensor_table[0].pos_0 = pmArrayRead_ptr_table + 16U;
        BodySensor_table[0].T = pmArrayRead_ptr_table + 2U;
        BodySensor_table[0].outputScaling = real_T_table + 6U;
        BodySensor_table[1].n = 2U;
        BodySensor_table[1].sensorType = int32_T_table;
        BodySensor_table[1].pos_0 = pmArrayRead_ptr_table + 12U;
        BodySensor_table[1].T = pmArrayRead_ptr_table + 14U;
        BodySensor_table[1].outputScaling = real_T_table + 4U;
        BodySensor_table[2].n = 2U;
        BodySensor_table[2].sensorType = int32_T_table + 6U;
        BodySensor_table[2].pos_0 = pmArrayRead_ptr_table + 10U;
        BodySensor_table[2].T = pmArrayRead_ptr_table;
        BodySensor_table[2].outputScaling = real_T_table + 2U;
        BodySensor_table[3].n = 2U;
        BodySensor_table[3].sensorType = int32_T_table + 4U;
        BodySensor_table[3].pos_0 = pmArrayRead_ptr_table + 8U;
        BodySensor_table[3].T = pmArrayRead_ptr_table + 18U;
        BodySensor_table[3].outputScaling = real_T_table;
        BodySensor_table[4].n = 2U;
        BodySensor_table[4].sensorType = int32_T_table + 8U;
        BodySensor_table[4].pos_0 = pmArrayRead_ptr_table + 4U;
        BodySensor_table[4].T = pmArrayRead_ptr_table + 6U;
        BodySensor_table[4].outputScaling = real_T_table + 8U;
        /* starting table: BodyActuator_table */
        memset(BodyActuator_table, 0, sizeof(BodyActuator_table));
        /* starting table: GeneralJointEngine_table */
        memset(GeneralJointEngine_table, 0, sizeof(GeneralJointEngine_table));
        GeneralJointEngine_table[0].scale = 1.0;
        GeneralJointEngine_table[0].lockTolerance = pmArrayRead_table + 64U;
        GeneralJointEngine_table[0].primitives = NameArrayRead_table;
        GeneralJointEngine_table[0].eventList = IndexArrayRead_table + 5U;
        GeneralJointEngine_table[0].poweredList = IndexArrayRead_table + 15U;
        GeneralJointEngine_table[0].icpoweredList = IndexArrayRead_table + 1U;
        GeneralJointEngine_table[0].icposition = pmArrayRead_table + 65U;
        GeneralJointEngine_table[0].icvelocity = pmArrayRead_table + 66U;
        GeneralJointEngine_table[0].sensor = Sensor_table;
        GeneralJointEngine_table[1].scale = 1.0;
        GeneralJointEngine_table[1].axis = AxisRead_table + 3U;
        GeneralJointEngine_table[1].lockTolerance = pmArrayRead_table + 70U;
        GeneralJointEngine_table[1].primitives = NameArrayRead_table + 6U;
        GeneralJointEngine_table[1].eventList = IndexArrayRead_table + 3U;
        GeneralJointEngine_table[1].poweredList = IndexArrayRead_table + 2U;
        GeneralJointEngine_table[1].icpoweredList = IndexArrayRead_table + 14U;
        GeneralJointEngine_table[1].icposition = pmArrayRead_table + 71U;
        GeneralJointEngine_table[1].icvelocity = pmArrayRead_table + 72U;
        GeneralJointEngine_table[1].sensor = Sensor_table + 5U;
        GeneralJointEngine_table[2].scale = 1.0;
        GeneralJointEngine_table[2].axis = AxisRead_table + 1U;
        GeneralJointEngine_table[2].lockTolerance = pmArrayRead_table + 53U;
        GeneralJointEngine_table[2].primitives = NameArrayRead_table + 3U;
        GeneralJointEngine_table[2].eventList = IndexArrayRead_table + 19U;
        GeneralJointEngine_table[2].poweredList = IndexArrayRead_table + 18U;
        GeneralJointEngine_table[2].icpoweredList = IndexArrayRead_table + 12U;
        GeneralJointEngine_table[2].icposition = pmArrayRead_table + 54U;
        GeneralJointEngine_table[2].icvelocity = pmArrayRead_table + 55U;
        GeneralJointEngine_table[2].sensor = Sensor_table + 4U;
        GeneralJointEngine_table[3].scale = 1.0;
        GeneralJointEngine_table[3].axis = AxisRead_table + 2U;
        GeneralJointEngine_table[3].lockTolerance = pmArrayRead_table + 59U;
        GeneralJointEngine_table[3].primitives = NameArrayRead_table + 1U;
        GeneralJointEngine_table[3].eventList = IndexArrayRead_table + 16U;
        GeneralJointEngine_table[3].poweredList = IndexArrayRead_table;
        GeneralJointEngine_table[3].icpoweredList = IndexArrayRead_table + 4U;
        GeneralJointEngine_table[3].icposition = pmArrayRead_table + 60U;
        GeneralJointEngine_table[3].icvelocity = pmArrayRead_table + 61U;
        GeneralJointEngine_table[3].sensor = Sensor_table + 1U;
        GeneralJointEngine_table[4].scale = 1.0;
        GeneralJointEngine_table[4].axis = AxisRead_table;
        GeneralJointEngine_table[4].lockTolerance = pmArrayRead_table + 47U;
        GeneralJointEngine_table[4].primitives = NameArrayRead_table + 5U;
        GeneralJointEngine_table[4].eventList = IndexArrayRead_table + 13U;
        GeneralJointEngine_table[4].poweredList = IndexArrayRead_table + 20U;
        GeneralJointEngine_table[4].icpoweredList = IndexArrayRead_table + 11U;
        GeneralJointEngine_table[4].icposition = pmArrayRead_table + 48U;
        GeneralJointEngine_table[4].icvelocity = pmArrayRead_table + 49U;
        GeneralJointEngine_table[4].sensor = Sensor_table + 3U;
        GeneralJointEngine_table[5].scale = 1.0;
        GeneralJointEngine_table[5].lockTolerance = pmArrayRead_table + 41U;
        GeneralJointEngine_table[5].primitives = NameArrayRead_table + 4U;
        GeneralJointEngine_table[5].eventList = IndexArrayRead_table + 6U;
        GeneralJointEngine_table[5].poweredList = IndexArrayRead_table + 10U;
        GeneralJointEngine_table[5].icpoweredList = IndexArrayRead_table + 7U;
        GeneralJointEngine_table[5].icposition = pmArrayRead_table + 42U;
        GeneralJointEngine_table[5].icvelocity = pmArrayRead_table + 43U;
        GeneralJointEngine_table[5].sensor = Sensor_table + 2U;
        GeneralJointEngine_table[6].lockTolerance = pmArrayRead_table + 36U;
        GeneralJointEngine_table[6].primitives = NameArrayRead_table + 2U;
        GeneralJointEngine_table[6].eventList = IndexArrayRead_table + 9U;
        GeneralJointEngine_table[6].poweredList = IndexArrayRead_table + 8U;
        GeneralJointEngine_table[6].icpoweredList = IndexArrayRead_table + 17U;
        GeneralJointEngine_table[6].icposition = pmArrayRead_table + 37U;
        GeneralJointEngine_table[6].icvelocity = pmArrayRead_table + 38U;
        /* starting table: Joint_table */
        memset(Joint_table, 0, sizeof(Joint_table));
        Joint_table[0].blockName = "vmrl_test_fourbar/Revolute2";
        Joint_table[0].pos_0 = pmArrayRead_table + 56U;
        Joint_table[0].rel_0 = pmArrayRead_table + 57U;
        Joint_table[0].type = 2;
        Joint_table[0].compile = GeneralJointEngine_table + 3U;
        Joint_table[0].pred = Joint_table + 3U;
        Joint_table[1].blockName = "vmrl_test_fourbar/Revolute";
        Joint_table[1].pos_0 = pmArrayRead_table + 44U;
        Joint_table[1].rel_0 = pmArrayRead_table + 45U;
        Joint_table[1].type = 2;
        Joint_table[1].compile = GeneralJointEngine_table + 4U;
        Joint_table[1].pred = Joint_table + 4U;
        Joint_table[2].isReversed = 1;
        Joint_table[2].blockName = "vmrl_test_fourbar/Weld1";
        Joint_table[2].pos_0 = pmArrayRead_table + 62U;
        Joint_table[2].rel_0 = pmArrayRead_table + 63U;
        Joint_table[2].type = 2;
        Joint_table[2].compile = GeneralJointEngine_table;
        Joint_table[2].pred = Joint_table + 5U;
        Joint_table[3].blockName = "vmrl_test_fourbar/Revolute1";
        Joint_table[3].pos_0 = pmArrayRead_table + 50U;
        Joint_table[3].rel_0 = pmArrayRead_table + 51U;
        Joint_table[3].type = 2;
        Joint_table[3].compile = GeneralJointEngine_table + 2U;
        Joint_table[3].pred = Joint_table + 1U;
        Joint_table[4].blockName = "vmrl_test_fourbar/Weld";
        Joint_table[4].pos_0 = pmArrayRead_table + 39U;
        Joint_table[4].rel_0 = pmArrayRead_table + 40U;
        Joint_table[4].type = 2;
        Joint_table[4].compile = GeneralJointEngine_table + 5U;
        Joint_table[4].pred = Joint_table + 5U;
        Joint_table[5].blockName = "PermeatingWeld";
        Joint_table[5].pos_0 = pmArrayRead_table + 1U;
        Joint_table[5].rel_0 = pmArrayRead_table + 1U;
        Joint_table[5].type = 2;
        Joint_table[5].compile = GeneralJointEngine_table + 6U;
        Joint_table[5].pred = Joint_table + 5U;
        /* starting table: BodyEngine_table */
        memset(BodyEngine_table, 0, sizeof(BodyEngine_table));
        BodyEngine_table[0].J_0 = pmArrayRead_table + 9U;
        BodyEngine_table[0].pos_0 = pmArrayRead_table + 10U;
        BodyEngine_table[0].mass = pmArrayRead_table + 8U;
        BodyEngine_table[0].sensor = BodySensor_table + 1U;
        BodyEngine_table[0].input = BodyActuator_table + 3U;
        BodyEngine_table[0].massinertia = BodyActuator_table + 1U;
        BodyEngine_table[0].transform2D = pmArrayRead_table + 11U;
        BodyEngine_table[1].J_0 = pmArrayRead_table + 15U;
        BodyEngine_table[1].pos_0 = pmArrayRead_table + 16U;
        BodyEngine_table[1].mass = pmArrayRead_table + 14U;
        BodyEngine_table[1].sensor = BodySensor_table;
        BodyEngine_table[1].input = BodyActuator_table;
        BodyEngine_table[1].massinertia = BodyActuator_table + 2U;
        BodyEngine_table[1].transform2D = pmArrayRead_table + 17U;
        BodyEngine_table[2].J_0 = pmArrayRead_table + 21U;
        BodyEngine_table[2].pos_0 = pmArrayRead_table + 22U;
        BodyEngine_table[2].mass = pmArrayRead_table + 20U;
        BodyEngine_table[2].sensor = BodySensor_table + 2U;
        BodyEngine_table[2].input = BodyActuator_table + 4U;
        BodyEngine_table[2].massinertia = BodyActuator_table + 5U;
        BodyEngine_table[2].transform2D = pmArrayRead_table + 23U;
        BodyEngine_table[3].J_0 = pmArrayRead_table + 27U;
        BodyEngine_table[3].pos_0 = pmArrayRead_table + 28U;
        BodyEngine_table[3].mass = pmArrayRead_table + 26U;
        BodyEngine_table[3].sensor = BodySensor_table + 3U;
        BodyEngine_table[3].input = BodyActuator_table + 6U;
        BodyEngine_table[3].massinertia = BodyActuator_table + 7U;
        BodyEngine_table[3].transform2D = pmArrayRead_table + 29U;
        BodyEngine_table[4].J_0 = pmArrayRead_table + 33U;
        BodyEngine_table[4].pos_0 = pmArrayRead_table + 34U;
        BodyEngine_table[4].mass = pmArrayRead_table + 32U;
        BodyEngine_table[4].sensor = BodySensor_table + 4U;
        BodyEngine_table[4].input = BodyActuator_table + 8U;
        BodyEngine_table[4].massinertia = BodyActuator_table + 9U;
        BodyEngine_table[4].transform2D = pmArrayRead_table + 35U;
        BodyEngine_table[5].J_0 = pmArrayRead_table + 5U;
        BodyEngine_table[5].pos_0 = pmArrayRead_table + 3U;
        BodyEngine_table[5].mass = pmArrayRead_table + 4U;
        BodyEngine_table[5].sensor = BodySensor_table + 5U;
        BodyEngine_table[5].input = BodyActuator_table + 10U;
        BodyEngine_table[5].massinertia = BodyActuator_table + 11U;
        /* starting table: Body_table */
        memset(Body_table, 0, sizeof(Body_table));
        Body_table[0].blockName = "vmrl_test_fourbar/Body";
        Body_table[0].compile = BodyEngine_table;
        Body_table[0].pred = Body_table + 5U;
        Body_table[1].blockName = "vmrl_test_fourbar/Body1";
        Body_table[1].compile = BodyEngine_table + 1U;
        Body_table[1].pred = Body_table;
        Body_table[2].blockName = "vmrl_test_fourbar/Body2";
        Body_table[2].compile = BodyEngine_table + 2U;
        Body_table[2].pred = Body_table + 1U;
        Body_table[3].blockName = "vmrl_test_fourbar/Body3";
        Body_table[3].compile = BodyEngine_table + 3U;
        Body_table[3].pred = Body_table + 2U;
        Body_table[4].blockName = "vmrl_test_fourbar/Body4";
        Body_table[4].compile = BodyEngine_table + 4U;
        Body_table[4].pred = Body_table + 5U;
        Body_table[5].blockName = "PermeatingBody";
        Body_table[5].compile = BodyEngine_table + 5U;
        Body_table[5].pred = Body_table + 5U;
        /* starting table: Joint_ptr_table */
        memset(Joint_ptr_table, 0, sizeof(Joint_ptr_table));
        Joint_ptr_table[0] = Joint_table;
        Joint_ptr_table[1] = Joint_table + 3U;
        Joint_ptr_table[2] = Joint_table + 1U;
        Joint_ptr_table[3] = Joint_table + 4U;
        Joint_ptr_table[4] = Joint_table + 5U;
        Joint_ptr_table[5] = Joint_table + 2U;
        /* starting table: Constraint_table */
        memset(Constraint_table, 0, sizeof(Constraint_table));
        Constraint_table[0].joint1 = Joint_table;
        Constraint_table[0].joint2 = Joint_table + 2U;
        Constraint_table[0].pos1_0 = pmArrayRead_table + 67U;
        Constraint_table[0].pos2_0 = pmArrayRead_table + 68U;
        Constraint_table[0].blockName = "vmrl_test_fourbar/Revolute3";
        Constraint_table[0].type = 4;
        Constraint_table[0].compile = GeneralJointEngine_table + 1U;
        /* starting table: Branch_table */
        memset(Branch_table, 0, sizeof(Branch_table));
        Branch_table[0].njoints = 1;
        Branch_table[0].body = Body_ptr_table + 5U;
        Branch_table[0].joint = Joint_ptr_table + 5U;
        Branch_table[0].pred = Branch_table + 2U;
        Branch_table[1].njoints = 4;
        Branch_table[1].body = Body_ptr_table;
        Branch_table[1].joint = Joint_ptr_table;
        Branch_table[1].pred = Branch_table + 2U;
        Branch_table[2].njoints = 1;
        Branch_table[2].body = Body_ptr_table + 4U;
        Branch_table[2].joint = Joint_ptr_table + 4U;
        Branch_table[2].pred = Branch_table + 2U;
        /* starting table: Body_ptr_table */
        memset(Body_ptr_table, 0, sizeof(Body_ptr_table));
        Body_ptr_table[0] = Body_table + 3U;
        Body_ptr_table[1] = Body_table + 2U;
        Body_ptr_table[2] = Body_table + 1U;
        Body_ptr_table[3] = Body_table;
        Body_ptr_table[4] = Body_table + 5U;
        Body_ptr_table[5] = Body_table + 4U;
        /* starting table: Connect_table */
        memset(Connect_table, 0, sizeof(Connect_table));
        Connect_table[0].n = 2;
        Connect_table[0].branch = Branch_ptr_table;
        /* starting table: Branch_ptr_table */
        memset(Branch_ptr_table, 0, sizeof(Branch_ptr_table));
        Branch_ptr_table[0] = Branch_table + 1U;
        Branch_ptr_table[1] = Branch_table;
        Branch_ptr_table[2] = Branch_table;
        Branch_ptr_table[3] = Branch_table + 1U;
        Branch_ptr_table[4] = Branch_table;
        Branch_ptr_table[5] = Branch_table + 1U;
        Branch_ptr_table[6] = Branch_table + 2U;
        Branch_ptr_table[7] = Branch_table + 2U;
        /* starting table: Recursion_table */
        memset(Recursion_table, 0, sizeof(Recursion_table));
        Recursion_table[0].nLeafBranches = 2;
        Recursion_table[0].nTrunkBranches = 1;
        Recursion_table[0].leaf = Branch_ptr_table + 2U;
        Recursion_table[0].trunk = Branch_ptr_table + 7U;
        Recursion_table[0].trunkConnectors = Connect_ptr_table;
        /* starting table: Connect_ptr_table */
        memset(Connect_ptr_table, 0, sizeof(Connect_ptr_table));
        Connect_ptr_table[0] = Connect_table;
        /* starting table: MachineData_table */
        memset(MachineData_table, 0, sizeof(MachineData_table));
        MachineData_table[0].numBlock1States = 6;
        MachineData_table[0].numBlock1Outputs = 60;
        MachineData_table[0].rTol = 0.0001;
        MachineData_table[0].aTol = 0.0001;
        MachineData_table[0].sqrtEps = 1.4901161193847656E-008;
        MachineData_table[0].linearAssemblyTolerance = 0.001;
        MachineData_table[0].angularAssemblyTolerance = 0.001;
        MachineData_table[0].redundancyAnalysisToleranceType = 1;
        MachineData_table[0].redundancyAnalysisTolerance = 1.0E-014;
        MachineData_table[0].system = "vmrl_test_fourbar/Ground";
        MachineData_table[0].gravity = pmArrayRead_table + 2U;
        MachineData_table[0].recurse = Recursion_table;
        MachineData_table[0].mode = 2;
        MachineData_table[0].solve = 1;
        MachineData_table[0].linFixedPerturbation = 1;
        MachineData_table[0].linPerturbationSize = 0.00001;
        /* starting table: WarningFlags_table */
        memset(WarningFlags_table, 0, sizeof(WarningFlags_table));
        WarningFlags_table[0].warnOnRedundantConstraints = 1;
        /* starting table: Mechanism_table */
        memset(Mechanism_table, 0, sizeof(Mechanism_table));
        Mechanism_table[0].nbranches = 3;
        Mechanism_table[0].nconstraints = 1;
        Mechanism_table[0].generatingCode = 1;
        Mechanism_table[0].branch = Branch_ptr_table + 4U;
        Mechanism_table[0].constraint = Constraint_ptr_table;
        Mechanism_table[0].data = MachineData_table;
        Mechanism_table[0].nruntimeData = 633U;
        Mechanism_table[0].runtimeData = real_T_table + 16U;
        Mechanism_table[0].allowedSimulationDimensions = 4;
        Mechanism_table[0].transform2D = pmArrayRead_table + 73U;
        Mechanism_table[0].warningFlags = WarningFlags_table;
        /* starting table: Constraint_ptr_table */
        memset(Constraint_ptr_table, 0, sizeof(Constraint_ptr_table));
        Constraint_ptr_table[0] = Constraint_table;
        _mechanism = Mechanism_table;
        _mechanism->mapRuntimeData = rt_map_mechanism_params_vmrl_test_fourbar_1d6fdf5b;
    }
    return _mechanism;
}
